# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: DotNetCoreInstaller@0
  displayName: 'Install .net core 3.1 (preview)'
  inputs:
    version: '3.1.100-preview2-014569'

- script: dotnet build source/fluentlang.sln --configuration $(buildConfiguration)
  displayName: 'dotnet build $(buildConfiguration)'
- task: DotNetCoreCLI@2
  displayName: 'Run Tests $(buildConfiguration)'
  inputs:
    command: test
    projects: '**/*Tests*.csproj'
    arguments: '--configuration $(buildConfiguration)'

- task: DotNetCoreCLI@2
  displayName: Nuget Pack
  condition: eq(variables['Build.SourceBranch'], 'refs/heads/master')
  inputs:
    command: 'pack'
    packagesToPack: '**/Runtime.csproj'
    outputDir: '$(Build.ArtifactStagingDirectory)'
    versioningScheme: byPrereleaseNumber

- task: DotNetCoreCLI@2
  displayName: Nuget Push
  inputs:
    command: custom
    custom: nuget
    arguments: >
      push $(Build.ArtifactStagingDirectory)/**/*.nupkg $(Build.ArtifactStagingDirectory)/**/*.snupkg
      -s https://api.nuget.org/v3/index.json
      -k $(NuGetSourceServerApiKey)