namespace FluentLang.Compiler.Diagnostics
{
	public enum ErrorCode
	{
		SyntaxError,
		DuplicateInterfaceDeclaration,
		DuplicateMethodDeclaration,
		InterfaceNotFound,
		CannotReferenceSelfAsAdditiveInterface,
		InvalidParseTree,
		MethodNotFound,
		AmbigiousInterfaceReference,
		AmbigiousMethodReference,
		MismatchedTypes,
		CanOnlyPatchInterface,
		CannotMixInNonInterface,
		CannotPatchInMethodWithoutParameters,
		ResultantTypeOfObjectPatchingExpressionIsNotSubtypeOfFirstParameterOfPatchedInMethod,
		InvalidArgument,
		InvalidIntegerLiteral,
		IntegerLiteralOutOfRange,
		InvalidCharLiteral,
		InvalidRealLiteral,
		NonBooleanCondition,
		NoBestType,
		InvalidLocalReference,
		MemberNotFound,
		LastStatementMustBeReturnStatement,
		OnlyLastStatementCanBeReturnStatement,
		ReturnTypeDoesNotMatch,
		MethodMustContainAtLeastOneStatement,
		HidesLocal,
	}
}
